#!/usr/bin/env bash
# Build the iPhone app: Rust core -> static libs -> Xcode project.
#
#   ./ios/build.sh              # libs + generate FantasyAgent.xcodeproj
#   ./ios/build.sh --open       # ...and open it in Xcode
#   ./ios/build.sh --sim        # also build for the simulator
#   ./ios/build.sh --debug      # debug profile (much faster to compile)
#   ./ios/build.sh --testflight # archive and upload to TestFlight
#
# TestFlight needs App Store Connect API credentials:
#   ASC_KEY_ID=XXXXXXXXXX ASC_ISSUER_ID=<uuid> ./ios/build.sh --testflight
#
# Then in Xcode: pick your device, set a signing team, and hit Run.
set -euo pipefail

IOS_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$IOS_DIR/.." && pwd)"
PROFILE="release"
BUILD_SIM=0
OPEN=0
UPLOAD=0

for arg in "$@"; do
    case "$arg" in
        --debug) PROFILE="debug" ;;
        --sim)   BUILD_SIM=1 ;;
        --open)  OPEN=1 ;;
        --testflight) UPLOAD=1 ;;
        -h|--help) sed -n '2,13p' "$0"; exit 0 ;;
        *) echo "unknown flag: $arg" >&2; exit 2 ;;
    esac
done

# rustup is a multiplexer that dispatches on argv[0]; on some installs the
# `rustup` link is missing even though the binary is there. Recreate it in a
# temp dir rather than touching the user's toolchain.
rustup_bin() {
    if command -v rustup >/dev/null 2>&1; then
        command -v rustup
        return
    fi
    local shim="${TMPDIR:-/tmp}/sa-rustup/rustup"
    mkdir -p "$(dirname "$shim")"
    ln -sf "$(command -v cargo)" "$shim"
    echo "$shim"
}

RUSTUP="$(rustup_bin)"

echo "==> Ensuring iOS targets"
TARGETS=(aarch64-apple-ios)
[ "$BUILD_SIM" -eq 1 ] && TARGETS+=("$([ "$(uname -m)" = "arm64" ] && echo aarch64-apple-ios-sim || echo x86_64-apple-ios)")
for t in "${TARGETS[@]}"; do
    "$RUSTUP" target add "$t" >/dev/null 2>&1 || true
done

# Match the app's deployment target, or the linker warns on every object file
# that the library was built for a newer iOS than it is being linked into.
export IPHONEOS_DEPLOYMENT_TARGET="${IPHONEOS_DEPLOYMENT_TARGET:-17.0}"

FLAGS=(-p sa_ffi)
[ "$PROFILE" = "release" ] && FLAGS+=(--release)

for t in "${TARGETS[@]}"; do
    echo "==> Building sa_ffi for $t ($PROFILE)"
    ( cd "$REPO" && cargo build "${FLAGS[@]}" --target "$t" )
done

# Xcode looks these up by $(PLATFORM_NAME), so lay them out to match.
echo "==> Staging static libraries"
rm -rf "$IOS_DIR/build/lib"
mkdir -p "$IOS_DIR/build/lib/iphoneos"
cp "$REPO/target/aarch64-apple-ios/$PROFILE/libsa_ffi.a" "$IOS_DIR/build/lib/iphoneos/"
if [ "$BUILD_SIM" -eq 1 ]; then
    mkdir -p "$IOS_DIR/build/lib/iphonesimulator"
    simtarget="${TARGETS[1]}"
    cp "$REPO/target/$simtarget/$PROFILE/libsa_ffi.a" "$IOS_DIR/build/lib/iphonesimulator/"
fi

# Signing config. The Team ID identifies an Apple developer account, so it is
# written to a gitignored xcconfig rather than committed. Order of preference:
# an explicit $DEVELOPMENT_TEAM, then the OU field of an Apple Development
# certificate in the keychain (the parenthesised value in the identity name is
# a per-certificate id, not the team).
detect_team() {
    if [ -n "${DEVELOPMENT_TEAM:-}" ]; then
        echo "$DEVELOPMENT_TEAM"
        return
    fi
    local name
    name=$(security find-identity -v -p codesigning 2>/dev/null \
           | grep -o '"Apple Develop[^"]*"' | head -1 | tr -d '"')
    [ -z "$name" ] && return
    security find-certificate -c "$name" -p 2>/dev/null \
        | openssl x509 -noout -subject 2>/dev/null \
        | tr ',' '\n' | awk -F= '/OU=/{gsub(/ /,"",$2); print $2}' | head -1
}

TEAM="$(detect_team || true)"
CONFIG="$IOS_DIR/Local.xcconfig"
{
    echo "// Generated by ios/build.sh — not committed."
    echo "// Override with: DEVELOPMENT_TEAM=XXXXXXXXXX ./ios/build.sh"
    if [ -n "$TEAM" ]; then
        echo "DEVELOPMENT_TEAM = $TEAM"
        echo "CODE_SIGN_STYLE = Automatic"
    fi
} > "$CONFIG"

if [ -n "$TEAM" ]; then
    echo "==> Signing team: $TEAM"
else
    echo "==> No signing team found — set one in Xcode under"
    echo "    Signing & Capabilities, or re-run with DEVELOPMENT_TEAM=XXXXXXXXXX"
fi

if ! command -v xcodegen >/dev/null 2>&1; then
    echo "==> Installing XcodeGen (generates the .pbxproj from project.yml)"
    if command -v brew >/dev/null 2>&1; then
        brew install xcodegen
    else
        echo "!! XcodeGen not found and Homebrew is unavailable." >&2
        echo "   Install it from https://github.com/yonaskolb/XcodeGen and re-run." >&2
        exit 1
    fi
fi

echo "==> Generating Xcode project"
( cd "$IOS_DIR" && xcodegen generate --quiet )

if [ "$UPLOAD" -eq 1 ]; then
    # App Store Connect API credentials. The key is a secret, so it is read
    # from the standard location or the environment — never committed.
    : "${ASC_KEY_ID:?set ASC_KEY_ID (App Store Connect > Users and Access > Integrations)}"
    : "${ASC_ISSUER_ID:?set ASC_ISSUER_ID (the UUID on that same page)}"
    KEY_PATH="${ASC_KEY_PATH:-$HOME/.appstoreconnect/private_keys/AuthKey_${ASC_KEY_ID}.p8}"
    [ -f "$KEY_PATH" ] || { echo "!! No API key at $KEY_PATH" >&2; exit 1; }

    ARCHIVE="$IOS_DIR/build/FantasyAgent.xcarchive"
    echo "==> Archiving (Release)"
    # -allowProvisioningUpdates lets Xcode create the distribution certificate
    # and App Store profile through the API key, so no manual portal work.
    xcodebuild -project "$IOS_DIR/FantasyAgent.xcodeproj" \
        -scheme FantasyAgent -sdk iphoneos -configuration Release \
        -archivePath "$ARCHIVE" \
        -allowProvisioningUpdates \
        -authenticationKeyPath "$KEY_PATH" \
        -authenticationKeyID "$ASC_KEY_ID" \
        -authenticationKeyIssuerID "$ASC_ISSUER_ID" \
        archive

    cat > "$IOS_DIR/build/ExportOptions.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>            <string>app-store-connect</string>
    <key>teamID</key>            <string>$TEAM</string>
    <key>uploadSymbols</key>     <true/>
    <key>destination</key>       <string>upload</string>
    <key>signingStyle</key>      <string>automatic</string>
</dict>
</plist>
PLIST

    echo "==> Uploading to TestFlight"
    xcodebuild -exportArchive \
        -archivePath "$ARCHIVE" \
        -exportOptionsPlist "$IOS_DIR/build/ExportOptions.plist" \
        -exportPath "$IOS_DIR/build/export" \
        -allowProvisioningUpdates \
        -authenticationKeyPath "$KEY_PATH" \
        -authenticationKeyID "$ASC_KEY_ID" \
        -authenticationKeyIssuerID "$ASC_ISSUER_ID"

    echo
    echo "==> Uploaded. Processing takes a few minutes; the build then appears"
    echo "    in App Store Connect > TestFlight."
    exit 0
fi

echo
echo "==> Done: $IOS_DIR/FantasyAgent.xcodeproj"
echo "    Open it, select your iPhone, then Run."
echo "    For TestFlight: ASC_KEY_ID=... ASC_ISSUER_ID=... ./ios/build.sh --testflight"
[ "$OPEN" -eq 1 ] && open "$IOS_DIR/FantasyAgent.xcodeproj"
exit 0
