#!/usr/bin/env bash
# Build the iPhone app: Rust core -> static libs -> Xcode project.
#
#   ./ios/build.sh              # libs + generate FantasyAgent.xcodeproj
#   ./ios/build.sh --open       # ...and open it in Xcode
#   ./ios/build.sh --sim        # also build for the simulator
#   ./ios/build.sh --debug      # debug profile (much faster to compile)
#   ./ios/build.sh --testflight # archive and upload to TestFlight
#
# TestFlight needs one of:
#   ASC_KEY_ID=XXXXXXXXXX ASC_ISSUER_ID=<uuid>        (API key, preferred)
#   APPLE_ID=you@example.com APP_SPECIFIC_PASSWORD=…  (appleid.apple.com)
#
# Then in Xcode: pick your device, set a signing team, and hit Run.
set -euo pipefail

IOS_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$IOS_DIR/.." && pwd)"
PROFILE="release"
BUILD_SIM=0
OPEN=0
UPLOAD=0

for arg in "$@"; do
    case "$arg" in
        --debug) PROFILE="debug" ;;
        --sim)   BUILD_SIM=1 ;;
        --open)  OPEN=1 ;;
        --testflight) UPLOAD=1 ;;
        -h|--help) sed -n '2,13p' "$0"; exit 0 ;;
        *) echo "unknown flag: $arg" >&2; exit 2 ;;
    esac
done

# rustup is a multiplexer that dispatches on argv[0]; on some installs the
# `rustup` link is missing even though the binary is there. Recreate it in a
# temp dir rather than touching the user's toolchain.
rustup_bin() {
    if command -v rustup >/dev/null 2>&1; then
        command -v rustup
        return
    fi
    local shim="${TMPDIR:-/tmp}/sa-rustup/rustup"
    mkdir -p "$(dirname "$shim")"
    ln -sf "$(command -v cargo)" "$shim"
    echo "$shim"
}

RUSTUP="$(rustup_bin)"

echo "==> Ensuring iOS targets"
TARGETS=(aarch64-apple-ios)
[ "$BUILD_SIM" -eq 1 ] && TARGETS+=("$([ "$(uname -m)" = "arm64" ] && echo aarch64-apple-ios-sim || echo x86_64-apple-ios)")
for t in "${TARGETS[@]}"; do
    "$RUSTUP" target add "$t" >/dev/null 2>&1 || true
done

# Match the app's deployment target, or the linker warns on every object file
# that the library was built for a newer iOS than it is being linked into.
export IPHONEOS_DEPLOYMENT_TARGET="${IPHONEOS_DEPLOYMENT_TARGET:-17.0}"

FLAGS=(-p sa_ffi)
[ "$PROFILE" = "release" ] && FLAGS+=(--release)

for t in "${TARGETS[@]}"; do
    echo "==> Building sa_ffi for $t ($PROFILE)"
    ( cd "$REPO" && cargo build "${FLAGS[@]}" --target "$t" )
done

# Xcode looks these up by $(PLATFORM_NAME), so lay them out to match.
echo "==> Staging static libraries"
rm -rf "$IOS_DIR/build/lib"
mkdir -p "$IOS_DIR/build/lib/iphoneos"
cp "$REPO/target/aarch64-apple-ios/$PROFILE/libsa_ffi.a" "$IOS_DIR/build/lib/iphoneos/"
if [ "$BUILD_SIM" -eq 1 ]; then
    mkdir -p "$IOS_DIR/build/lib/iphonesimulator"
    simtarget="${TARGETS[1]}"
    cp "$REPO/target/$simtarget/$PROFILE/libsa_ffi.a" "$IOS_DIR/build/lib/iphonesimulator/"
fi

# Signing config. The Team ID identifies an Apple developer account, so it is
# written to a gitignored xcconfig rather than committed. Order of preference:
# an explicit $DEVELOPMENT_TEAM, then the OU field of an Apple Development
# certificate in the keychain (the parenthesised value in the identity name is
# a per-certificate id, not the team).
detect_team() {
    if [ -n "${DEVELOPMENT_TEAM:-}" ]; then
        echo "$DEVELOPMENT_TEAM"
        return
    fi
    local name
    name=$(security find-identity -v -p codesigning 2>/dev/null \
           | grep -o '"Apple Develop[^"]*"' | head -1 | tr -d '"')
    [ -z "$name" ] && return
    security find-certificate -c "$name" -p 2>/dev/null \
        | openssl x509 -noout -subject 2>/dev/null \
        | tr ',' '\n' | awk -F= '/OU=/{gsub(/ /,"",$2); print $2}' | head -1
}

TEAM="$(detect_team || true)"
CONFIG="$IOS_DIR/Local.xcconfig"
{
    echo "// Generated by ios/build.sh — not committed."
    echo "// Override with: DEVELOPMENT_TEAM=XXXXXXXXXX ./ios/build.sh"
    if [ -n "$TEAM" ]; then
        echo "DEVELOPMENT_TEAM = $TEAM"
        echo "CODE_SIGN_STYLE = Automatic"
    fi
} > "$CONFIG"

if [ -n "$TEAM" ]; then
    echo "==> Signing team: $TEAM"
else
    echo "==> No signing team found — set one in Xcode under"
    echo "    Signing & Capabilities, or re-run with DEVELOPMENT_TEAM=XXXXXXXXXX"
fi

if ! command -v xcodegen >/dev/null 2>&1; then
    echo "==> Installing XcodeGen (generates the .pbxproj from project.yml)"
    if command -v brew >/dev/null 2>&1; then
        brew install xcodegen
    else
        echo "!! XcodeGen not found and Homebrew is unavailable." >&2
        echo "   Install it from https://github.com/yonaskolb/XcodeGen and re-run." >&2
        exit 1
    fi
fi

echo "==> Generating Xcode project"
( cd "$IOS_DIR" && xcodegen generate --quiet )

if [ "$UPLOAD" -eq 1 ]; then
    ARCHIVE="$IOS_DIR/build/FantasyAgent.xcarchive"
    EXPORT="$IOS_DIR/build/export"

    # Two ways to authenticate. The API key is preferred: it also lets Xcode
    # create the distribution certificate and App Store profile itself, which
    # an Apple Development certificate cannot cover. Apple ID plus an
    # app-specific password is supported because it is what most people
    # already have set up.
    AUTH=()
    MODE=""
    if [ -n "${ASC_ISSUER_ID:-}" ]; then
        : "${ASC_KEY_ID:?ASC_ISSUER_ID is set, so ASC_KEY_ID is required too}"
        KEY_PATH="${ASC_KEY_PATH:-$HOME/.appstoreconnect/private_keys/AuthKey_${ASC_KEY_ID}.p8}"
        [ -f "$KEY_PATH" ] || { echo "!! No API key at $KEY_PATH" >&2; exit 1; }
        AUTH=(-authenticationKeyPath "$KEY_PATH"
              -authenticationKeyID "$ASC_KEY_ID"
              -authenticationKeyIssuerID "$ASC_ISSUER_ID")
        MODE="apikey"
    elif [ -n "${APPLE_ID:-}" ] && [ -n "${APP_SPECIFIC_PASSWORD:-}" ]; then
        MODE="appleid"
    else
        cat >&2 <<'MSG'
!! No upload credentials. Use either:

   App Store Connect API key (preferred — can also create the distribution
   certificate and profile for you):
     ASC_KEY_ID=XXXXXXXXXX ASC_ISSUER_ID=<uuid> ./ios/build.sh --testflight

   or an Apple ID with an app-specific password from appleid.apple.com:
     APPLE_ID=you@example.com APP_SPECIFIC_PASSWORD=xxxx-xxxx-xxxx-xxxx \
       ./ios/build.sh --testflight
MSG
        exit 1
    fi

    echo "==> Archiving (Release, auth: $MODE)"
    xcodebuild -project "$IOS_DIR/FantasyAgent.xcodeproj" \
        -scheme FantasyAgent -sdk iphoneos -configuration Release \
        -archivePath "$ARCHIVE" \
        -allowProvisioningUpdates "${AUTH[@]}" \
        archive

    # With an API key xcodebuild can upload directly; with an Apple ID it
    # exports an .ipa that altool then ships.
    DESTINATION="upload"
    [ "$MODE" = "appleid" ] && DESTINATION="export"

    cat > "$IOS_DIR/build/ExportOptions.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>            <string>app-store-connect</string>
    <key>teamID</key>            <string>$TEAM</string>
    <key>uploadSymbols</key>     <true/>
    <key>destination</key>       <string>$DESTINATION</string>
    <key>signingStyle</key>      <string>automatic</string>
</dict>
</plist>
PLIST

    echo "==> Exporting"
    rm -rf "$EXPORT"
    xcodebuild -exportArchive \
        -archivePath "$ARCHIVE" \
        -exportOptionsPlist "$IOS_DIR/build/ExportOptions.plist" \
        -exportPath "$EXPORT" \
        -allowProvisioningUpdates "${AUTH[@]}"

    if [ "$MODE" = "appleid" ]; then
        IPA="$(find "$EXPORT" -name '*.ipa' | head -1)"
        [ -n "$IPA" ] || { echo "!! No .ipa was produced" >&2; exit 1; }
        echo "==> Uploading $IPA"
        # Password is passed via the environment so it never lands in argv,
        # where any other process on the machine could read it.
        APP_SPECIFIC_PASSWORD="$APP_SPECIFIC_PASSWORD" \
        xcrun altool --upload-app -f "$IPA" -t ios \
            -u "$APPLE_ID" -p "@env:APP_SPECIFIC_PASSWORD"
    fi

    echo
    echo "==> Uploaded. Processing takes a few minutes, then the build appears"
    echo "    in App Store Connect > TestFlight."
    exit 0
fi

echo
echo "==> Done: $IOS_DIR/FantasyAgent.xcodeproj"
echo "    Open it, select your iPhone, then Run."
echo "    For TestFlight: ASC_KEY_ID=... ASC_ISSUER_ID=... ./ios/build.sh --testflight"
[ "$OPEN" -eq 1 ] && open "$IOS_DIR/FantasyAgent.xcodeproj"
exit 0
